import {
  Box,
  Modal,
  Paper,
  styled,
  TextareaAutosize,
  TextField,
} from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";

const bgColors = {
  lightBlue: "#A4ECDA",
  darkgreen: "#008C87",
  skyBlue: "#00D9D2",
  LightMossGreen: "#CBFFB2",
  sunsetRed: "#F55D5D",
  borderLinear:
    "linear-gradient(180deg, rgba(0,140,135,1) 0%, rgba(0,140,135,1) 0%, rgba(0,212,255,1) 100%)",
  // lightSilver:'#D9D9D9'
  lightSilver: "#C3C3C3",
};
const colors = {
  black: "#000000",
  white: "#FFFFFF",
  red: "#FF0000",
  darkgreen: "#00736F",
  aquasky: "#01D9D1",
  bluishGreen: "#008C86",
  gray: "#757575",
};
const fontSize = {
  h1: "3rem",
  h2: "2.25rem", //36px
  h3: "1.875rem", //30px
  h24: "1.5rem", //24px
  h4: "1.25rem", //20px
  h18: "1.125rem", //18px
  h5: "1rem", //16px
  h6: "0.9rem", //14px
  h7: "0.8rem", //12px
  p: "0.75rem",
};
const fontWeight = {
  extrabold: 800,
  bold: 700,
  semibold: 600,
  medium: 500,
  p1: 400,
};
const GlobleStyle = styled(Box)(({ open }) => ({
  "& *": {
    fontFamily: "Poppins",
  },
  "& .css-1edfpdg-MuiTypography-root": {
    fontFamily: "Poppins",
  },
  "& .css-rizt0-MuiTypography-root": {
    fontFamily: "Poppins",
  },
  "& input[type=checkbox]": {
    cursor: "pointer",
    appearance: "none",
    minWidth: "16px",
    minHeight: "16px",
    backgroundColor: "#fff",
    border: "1px solid black",
    borderRadius: "2px",
    display: "inline-block",
  },
  "& .continue-btn": {
    backgroundColor: colors.darkGreen,
    color: colors.secondary,
    textTransform: "none",
    width: "80% !important",
    height: "45px !important",
    marginTop: "5% !important",
    marginLeft: "auto !important",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: colors.darkCyan,
    },
    "&:disabled": {
      opacity: "60%",
      backgroundColor: bgColors.brightCyan,
    },
  },
  "& .main-container": {
    backgroundColor: colors.neutralGrey,
    height: "400px",
    width: "400px",
    border: "1px solid black",
    display: "flex",
    alignItems: "center",
    margin: "auto",
    flexDirection: "column",
    width: "100%",
    height: "100vh",
    overflow: "hidden",
    fontFamily: "Poppins, Arial, sans-serif",
  },
  "& .input-container": {
    width: "80%",
    padding: "5%",
    margin: "auto",
  },
  "& .input-style": {
    width: "100%",
    height: "30px",
    borderRadius: "6px",
    border: "0.5px solid grey",
    display: "flex",
    boxSizing: "border-box",
    fontFamily: "Poppins",
  },
  "& .login-heading": {
    fontSize: fontSize.h5,
    fontWeight: fontWeight.semibold,
  },
  "& .error-msg": {
    color: colors.red || "#FF0000",
    textTransform: "none",
    width: "100%",
    marginLeft: "5%",
    display: "flex",
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.h7,
    textAlign: "start",
  },
  "& .label-text": {
    fontSize: fontSize.h5 || fontSize.h6,
    fontWeight: fontWeight.semibold || fontWeight.medium,
    textAlign: "left",
    color: "#666666",
  },
  "& .forgot-pass": {
    width: "50%",
    marginLeft: "10%",
    fontSize: fontSize.h6,
    fontWeight: fontWeight.semibold,
  },
  "& ul": {
    listStyleType: "none",
    paddingInlineStart: "0px",
  },
  "& li": {
    width: "max-content",
  },
  "& .parent-container": {
    fontFamily: "Poppins",
    padding: "2%",
    borderRadius: "1rem",
    border: "1px solid #00D9D2",
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: `calc(100vw - ${open ? "260px" : "80px"})`,
    overflowX: "hidden",
    boxSizing: "border-box",
  },
  "& .policies-container": {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    paddingBottom: "3%",
  },
  "& .policies-text": {
    fontSize: fontSize.h24,
    fontWeight: fontWeight.semibold,
    paddingBottom: "1%",
    fontFamily: "Poppins",
  },
  "& .create-policy": {
    backgroundColor: bgColors.skyBlue,
    color: colors.white,
    width: "fit-content",
    padding: "0.8rem",
    maxHeight: "fit-content",
    "&:disabled": {
      backgroundColor: "#C3C3C3",
      fontWeight: fontWeight.bold,
    },
  },
  "& .create-policy-label": {
    color: colors.white,
    backgroundColor: bgColors.skyBlue,
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    gap: "0.5rem",
    "&:disabled": {
      backgroundColor: "#C3C3C3",
      fontWeight: fontWeight.bold,
    },
  },
  "& .login-container": {
    width: "100%",
    height: "50vh",
    gap: "3rem",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginLeft: "3%",
    boxSizing: "border-box",
    fontFamily: "Poppins",
  },
  "& .login-input-container": {
    display: "flex",
    position: "relative",
    alignItems: "flex-start",
    flexDirection: "column",
    width: "100%",
    gap: "0.7rem",
    boxSizing: "border-box",
    fontFamily: "Poppins",
  },
  "& .grid-item-style": {
    width: "100%",
    alignItems: "start",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    paddingLeft: "70px",
    gap: "100px",
    boxSizing: "border-box",
    fontFamily: "Poppins",
  },
  "& img": {
    loading: "lazy",
  },
  "& .img-container": {
    width: "50%",
    alignItems: "center",
    justifyContent: "center",
    display: "flex",
    objectFit: "cover",
    backgroundColor: "#01D9D114",
  },
  "& .centered-box": {
    backgroundColor: "#FFFFFF",
    width: "80%",
    borderRadius: "5%",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
  },
  "& .try-text": {
    fontSize: fontSize.h6,
    fontWeight: fontWeight.medium,
    cursor: "pointer",
    color: bgColors.darkgreen,
    position: "relative",
    marginTop: "10%",
  },
  "& .box-align-center": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  "& .eclipse-style": {
    backgroundColor: "white",
    width: "100%",
    height: "100vh",
    borderRight: "1px inset #008C87",
    borderRadius: "0 50% 50% 0",
    boxShadow: "25px -4px 0px 0px #008C87",
    transform: "scaleY(1.2)",
    position: "relative",
    right: "20%",
  },
  "& .welcome-text": {
    fontWeight: fontWeight.medium,
    fontSize: fontSize.h2,
    color: "black",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    lineHeight: "0.8",
    fontFamily: "Poppins",
  },
  "& .centered-box-container": {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "537px",
    height: "100vh",
  },
  "& .welcome-img": {
    position: "absolute",
    zIndex: 1,
    height: "60%",
    width: "40%",
    margin: "auto",
  },
  "& .password-toggle-style": {
    cursor: "pointer",
    position: "absolute",
    alignItems: "center",
    justifyContent: "flex-end",
    zIndex: 10,
    right: "4.5rem",
    top: "35%",
  },
  "& .password-screen-toggle": {
    cursor: "pointer",
    position: "absolute",
    alignItems: "center",
    justifyContent: "flex-end",
    zIndex: 10,
    right: "5rem",
    top: "10%",
  },
  "& .get-link-btn": {
    height: "45px",
    width: "100%",
    fontSize: fontSize.h6,
    fontWeight: fontWeight.semibold,
    textTransform: "none",
  },
  "& .img-main-container": {
    backgroundColor: "#01D9D114",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    objectFit: "cover",
    height: "100vh",
  },
  "& .create-modal-heading": {
    fontSize: "1.25rem",
    fontFamily: "Poppins",
    fontWeight: "600",
    textAlign: "Left",
  },
  "& .policy-form-label": {
    display: "flex",
    gap: "4px",
    fontFamily: "Poppins",
    alignItems: "center",
  },
  "& .required-icon": {
    color: "red",
    fontWeight: fontWeight.medium,
    marginLeft: "4px",
  },
  "& .policy-btn": {
    marginTop: "10px",
    borderRadius: "20px",
    width: "fit-content",
    height: "3rem",
    lineHeight: "10px",
    textTransform: "none",
    padding: "0px 2%",
    fontFamily: "Poppins",
    background: colors.aquasky,
    color: colors.white,
    "&:hover": {
      backgroundColor: "#00b8a9",
    },
    "&:hover": {
      backgroundColor: "#00b8a9",
    },
  },
  "& .policy-submit-btn": {
    background: colors.aquasky,
    color: colors.white,
    borderRadius: "20px",
    width: "fit-content",
    maxHeight: "3rem",
    lineHeight: "10px",
    textTransform: "none",
    padding: "0px 4%",
  },
  "& .modal-input": {
    width: "100%",
    padding: "8px",
    marginTop: "4px",
    border: "1px solid rgba(0,0,0, .2)",
    borderRadius: "0.6rem",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "Poppins",
    "&:focus": {
      borderColor: "black",
      boxShadow: "0 0 0 1px black",
    },
    "&:hover": {
      borderColor: "black",
    },
    "&::placeholder": {
      fontWeight: 500,
      fontFamily: "Poppins",
      color: "black",
      opacity: "50%",
    },
  },
  "& *": {
    fontFamily: "Poppins",
    // width:'110%'
  },
  "& .css-1edfpdg-MuiTypography-root": {
    fontFamily: "Poppins",
  },
  "& .css-rizt0-MuiTypography-root ": {
    fontFamily: "Poppins",
  },
  "& input[type=checkbox]": {
    cursor: "pointer",
    appearance: "none",
    minWidth: "16px",
    minHeight: "16px",
    maxHeight: "16px",
    backgroundColor: "#fff",
    border: "1px solid black",
    borderRadius: "2px",
    display: "inline-block",
  },
  "& input[type=checkbox]:checked": {
    backgroundColor: "#C1E4E2",
    borderColor: "#008C87",
  },
  "& input[type=checkbox]::after": {
    content: '""',
    position: "relative",
    top: "5px",
    left: "50%",
    width: "6px",
    height: "10px",
    border: "solid #008C87",
    borderWidth: "0 2px 2px 0",
    transform: "translate(-50%, -50%) rotate(45deg)",
    display: "none",
  },
  "& input[type=checkbox]:checked::after": {
    display: "block",
  },

  "& .switch": {
    position: "relative",
    display: "inline-block",
    width: "41px",
    height: "18px",
  },
  "& .snackbar-content": {
    backgroundColor: "white",
    color: "black",
    fontFamily: "Poppins",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },

  "& .popover-modal-heading": {
    fontSize: fontSize?.h24,
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
  },
  "& .popover-label": {
    fontSize: fontSize?.h5,
    fontWeight: fontWeight.medium,
    fontFamily: "Poppins",
  },
  "& .popover-label-box": {
    display: "flex",
    gap: "0.8rem",
    alignItems: "flex-end",
  },
  "& .popover-value-text": {
    fontSize: fontSize?.h6,
    fontWeight: fontWeight.medium,
    opacity: "75%",
    fontFamily: "Poppins",
  },
  "& .switch input": {
    opacity: 0,
    width: 0,
    height: 0,
  },
  "& .slider": {
    position: "absolute",
    cursor: "pointer",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#D9D9D9",
    transition: ".4s",
    WebkitTransition: ".4s",
    border: "1px solid rgba(0, 0, 0, 0.5)",
  },
  "& .slider:before": {
    position: "absolute",
    content: '""',
    height: "16px",
    width: "16px",
    left: "2px",
    backgroundColor: colors.aquasky,
    transition: ".4s",
    WebkitTransition: ".4s",
  },
  "& input:checked + .slider": {
    backgroundColor: "#E3FBFA",
  },
  "& input:focus + .slider": {
    boxShadow: "0 0 1px #E3FBFA",
  },
  "& input:checked + .slider:before": {
    transform: "translateX(20px)",
    WebkitTransform: "translateX(20px)",
    msTransform: "translateX(20px)",
  },
  "& .slider.round": {
    borderRadius: "34px",
    width: "41px",
  },
  "& .slider.round:before": {
    borderRadius: "50%",
  },
  "& .btn-round": {
    border: "1px solid black",
    display: "inline-block",
    borderRadius: "50%",
    height: "30px",
    width: "30px",
  },
  "& .btn-style": {
    borderRadius: "20px",
    minWidth: "10vw",
    height: "45px",
    color: colors.white,
    lineHeight: "10px",
    textTransform: "none",
  },
  "& .get-started-btn": {
    height: "12vh",
    width: "13vw",
    fontFamily: "Poppins",
    fontSize: fontSize.h4,
    fontWeight: fontWeight.bold,
    backgroundColor: bgColors.skyBlue,
    color: colors.white,
    borderRadius: "30px",
    textTransform: "none",
  },
  "& .import-user-btn": {
    display: "flex",
    alignItems: "end",
    gap: "3px",
    fontSize: fontSize.h7,
    fontWeight: fontWeight.medium,
    cursor: "pointer",
  },
  "& .searchbar-style": {
    flex: 1,
    height: "33px",
    padding: "2%",
    fontFamily: "Poppins",
  },
  "& .parent-container": false
    ? {
        padding: "2%",
        borderRadius: "1rem",
        border: "1px solid #00D9D2",
        fontFamily: "Poppins",
        display: "flex",
        flexDirection: "column",
        width: "98%",
        // maxWidth: `calc(100vw - ${open ? "260px" : "80px"})`,
        margin: "auto",
        overflowX: "hidden",
        marginTop: "2%",
      }
    : {
        padding: "2%",
        borderRadius: "1rem",
        border: "1px solid #00D9D2",
        fontFamily: "Poppins",
        display: "flex",
        flexDirection: "column",
        // width: "100%",
        maxWidth: `calc(100vw - ${open ? "260px" : "80px"})`,
        // margin: 'auto',
        overflowX: "hidden",
        // marginLeft: "-2%",
      },

  "& .custom-dropdown": {
    width: "200px",
    position: "absolute",
    zIndex: 5,
    left: "38%",
    backgroundColor: "white",
    borderRadius: "10px",
    border: "1px solid black",
  },

  "& .action-dropdown": {
    position: "absolute",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    width: "220px",
    zIndex: 5,
    right: 1,
    backgroundColor: "white",
    borderRadius: "10px",
    border: "1px solid black",
    boxSizing: "border-box",
    flexWrap: "wrap",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
  "& .menu-item-opacity": {
    opacity: "70%",
  },
  "& .input-box-container": {
    mb: 2,
    mt: 2,
    display: "flex",
    flexDirection: "column",
    gap: "1.5vh",
  },
  "& .menu-item": {
    fontWeight: "medium",
    fontFamily: "Poppins",
    fontSize: fontSize.h6,
    width: "100%",
    "&:hover": {
      color: "#008C86",
      // backgroundImage: `url(${bgImg})`,
      backgroundSize: "30% 70%",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "content",
      borderBottomRightRadius: "100px",
      backgroundPositionX: "-38%",
      backgroundPositionY: "50%",
    },
    "&:active": {
      color: "#008C86",
      // backgroundImage: `url(${bgImg})`,
      backgroundSize: "30% 70%",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "content",
      borderBottomRightRadius: "100px",
      backgroundPositionX: "-38%",
      backgroundPositionY: "50%",
    },
  },
  "& .align-center-space-between": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  "& .current-version-box": {
    display: "flex",
    gap: ".5rem",
    flexDirection: "column",
  },
  "& .version-heading-style": {
    fontSize: fontSize.h7,
    opacity: "60%",
    fontWeight: fontWeight.medium,
    marginLeft: "2%",
    fontFamily: "Poppins",
  },
  "& .id-main-heading-style": {
    fontSize: fontSize.h7,
    opacity: "80%",
    fontWeight: fontWeight.medium,
    fontFamily: "Poppins",
  },
  "& .id-main-heading-style, & .version-heading-style": {
    margin: "0",
  },
  "& .policy-status": {
    fontFamily: "Poppins",
    fontSize: "12px",
    opacity: "70%",
    // padding: "0.5%",
    borderRadius: "20px",
    // marginLeft: "5px",
    fontWeight: fontWeight?.semibold,
  },
  "& .policy-status-box": {
    display: "flex",
    backgroundColor: "#C6F2F0",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
  },

  "& .inactive-status-box": {
    display: "flex",
    backgroundColor: "lightgrey",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.1rem 0.4rem",
  },
  "& .policy-inactive": {
    backgroundColor: "lightgrey",
    // alignItems: "center",
    // justifyContent: "center",
    // width: "fit-content",
    // borderRadius: "20px",
    // padding: "0.1rem 0.4rem",
  },
  "& .evidence-status-box": {
    display: "flex",
    backgroundColor: "#C6F2F0",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
    gap: "5px",
  },
  "& .red-status-box": {
    display: "flex",
    backgroundColor: "#FFC5C5",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
  },
  "& .red-status-box-label": {
    fontFamily: "Poppins",
    fontSize: "12px",
    // opacity: "60%",
    color: "#711C16",
    // padding: "0.5%",
    borderRadius: "20px",
    marginLeft: "5px",
    fontWeight: fontWeight?.semibold,
  },
  "& .yellow-status-box": {
    display: "flex",
    backgroundColor: "#FFEFBC",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
  },
  "& .green-status-box": {
    display: "flex",
    backgroundColor: "#CEFFFE",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
  },
  "& .green-status-box-label": {
    fontFamily: "Poppins",
    fontSize: "12px",
    // opacity: "60%",
    color: "#004D49",
    // padding: "0.5%",
    borderRadius: "20px",
    marginLeft: "5px",
    fontWeight: fontWeight?.semibold,
  },
  "& .status-box": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
    boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
  },
  "& .status-box-label": {
    fontFamily: "Poppins",
    fontSize: "12px",
    borderRadius: "20px",
    marginLeft: "5px",
    fontWeight: fontWeight?.semibold,
  },
  "& .icon-status-box": {
    display: "flex",
    gap: "4px",
    alignItems: "center",
  },
  "& .icon-status-style": {
    position: "relative",
    // top: "0.1rem",
  },
  "& .policy-not-active-box": {
    display: "flex",
    backgroundColor: "#F2DCC6",
    alignItems: "center",
    justifyContent: "center",
    width: "fit-content",
    borderRadius: "20px",
    padding: "0.4rem",
    gap: "5px",
  },

  "& .not-active": {
    color: "#AB2E00",
  },
  "& .status-version-box": {
    display: "flex",
    alignItems: "center",
    gap: "0.8rem",
    width: "100%",
  },
  "& .active": {
    color: "#008C86",
  },
  "& .add-user-input": {
    border: "0.5px solid black",
    borderRadius: "10px",
  },
  "& .description-text": {
    fontFamily: "Poppins",
    paddingBottom: "2%",
    whiteSpace: "pre-line",
    wordBreak: "break-word", // 👈 important
    overflowWrap: "break-word",
  },
  "& .ui-text": {
    whiteSpace: "pre-line",
    wordBreak: "break-word", // 👈 important
    overflowWrap: "break-word",
  },
  "& .import-user-input": {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },

  "& .select-role-box": {
    display: "flex",
    justifyContent: "start",
    gap: "20px",
    marginTop: "3%",
  },
  "& .centred-box": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  "& .font-h4-semibold": {
    fontSize: fontSize.h4,
    fontWeight: fontWeight.semibold,
  },
  "& .role-checkbox-container": {
    margin: "4%",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    WebkitTapHighlightColor: "transparent",
    userSelect: "none",
  },
  "& .filter-date-box": {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    margin: "4%",
  },
  "& .search-container": {
    display: "flex",
    flexWrap: "wrap",
    // margin: "8% 0 8% 0",
  },
  "& .company-logo": {
    // width: "100%",
    // height: "100%",
    // borderRadius: "50%",
    maxWidth: " 100px",
    maxHeight: "100px",
    display: "block",
  },
  "& img": {
    loading: "lazy",
  },

  "& .search-bar-style": {
    width: "80%",
    marginLeft: "8%",
    height: "6vh",
    // borderRadius: "20px",
    // backgroundColor: "#E5E2E3",
    padding: "5%",
  },
  "& .search-bar-style::placeholder": {
    color: "rgba(0, 0, 0, 0.5)",
  },
  "& .manage-btn": {
    height: "33px",
    border: "2px solid #01D9D1",
    minWidth: "100px",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    backgroundColor: "white !important",
    whiteSpace: "nowrap",
  },
  "& .mfa-parent-container": {
    width: "80%",
    margin: "auto",
    marginTop: "10%",
  },
  "& .clear-btn": {
    fontSize: fontSize.h6,
    fontWeight: fontWeight.p1,
    color: colors.aquasky,
    opacity: "70%",
    width: "100%",
    cursor: "pointer",
  },
  "& .edit-text": {
    fontFamily: "Poppins",
    fontSize: fontSize.h4,
    fontWeight: fontWeight.semibold,
    marginLeft: "7%",
    marginTop: "5%",
    width: "14rem",
    opacity: "70%",
  },

  "& .filter-btn-container": {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    gap: "20px",
    marginLeft: "7%",
    marginBottom: "2%",
    position: "sticky",
    bottom: 0,
    backgroundColor: "white",
    zIndex: 10,
    paddingBottom: "0.2rem",
  },
  "& .all-user-container": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "75%",
  },
  "& .all-user-text": {
    fontWeight: fontWeight.bold,
    fontSize: fontSize.h5,
  },
  "& .select-all-user": {
    fontWeight: fontWeight.medium,
    fontSize: fontSize.h7,
  },
  "& .more-option-style": {
    fontWeight: fontWeight.medium,
    fontSize: fontSize.h7,
    cursor: "pointer",
    color: colors.bluishGreen,
    padding: "0.5% 1%",
    // backgroundColor: bgColors.LightMossGreen,
    backgroundColor: "#CFFFFD",
    borderRadius: "12px",
    border: `0.5px solid ${colors.bluishGreen}`,
  },
  "& .delete-option": {
    fontWeight: fontWeight.medium,
    fontSize: fontSize.h7,
    cursor: "pointer",
    color: colors.red,
    padding: "0.5% 1%",
    backgroundColor: bgColors.sunsetRed,
    borderRadius: "12px",
    // border: `1px solid ${colors.darkgreen}`,
  },
  "& .delete-style": {
    cursor: "pointer",
    color: colors.red,
  },
  "& .align-between": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: "1.5rem",
  },
  "& .download-btn-container": {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "center",
    gap: "1rem",
    marginTop: "1rem",
  },
  "& .manage-btn-other": {
    minWidth: "130px",
  },
  "& .manage-btn-label": {
    color: "black",
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    width: "100%",
    fontWeight: fontWeight.medium,
    fontSize: fontSize.p,
    gap: "0.5rem",
    "&:disabled": {
      opacity: "70%",
    },
  },

  "& .box-align-center": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  "&  input::-webkit-outer-spin-button, input::-webkit-inner-spin-button, input::hover":
    {
      webkitAppearance: "none",
      margin: 0,
    },

  "& input[type=number], input[type=number]::hover": {
    mozAppearance: "textfield",
  },

  "& .error-msg": {
    fontFamily: "Poppins",
    fontSize: fontSize.h7,
    color: "red",
    wordBreak: "break-word",
    overflowWrap: "anywhere",
    minWidth: 0,
  },

  "& .tool-tip-style": {
    cursor: "pointer",
  },

  "& .centered-box-container": {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "537px",
    height: "100vh",
  },

  "& .welcome-img": {
    position: "absolute",
    zIndex: 1,
    height: "60%",
    width: "40%",
    margin: "auto",
    top: "28vh",
  },

  "& .password-toggle-style": {
    cursor: "pointer",
    position: "absolute",
    alignItems: "center",
    justifyContent: "flex-end",
    zIndex: 10,
    right: "4rem",
    top: "38%",
  },
  "& .apply-filter": {
    backgroundColor: bgColors.skyBlue,
    color: colors.white,
    fontWeight: fontWeight.medium,
    width: "80px",
    marginTop: 20,
  },
  "& .cancel-filter": {
    backgroundColor: bgColors.lightSilver,
    color: colors.white,
    fontWeight: fontWeight.medium,
    width: "70px",
  },
  "& .filter-box": {
    fontFamily: "Poppins",
    display: "flex",
    alignItems: "baseline",
    gap: "10px",
    width: "100%",
    maxWidth: "180px",
    flexWrap: "wrap",
  },
  "& .selected-filter": {
    display: "flex",
    flexWrap: "wrap",
    border: "1px solid #01D9D1",
    borderRadius: "20px",
    padding: "5px 15px",
    maxWidth: "200px",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    fontSize: fontSize?.p,
    textAlign: "center",
    gap: "10px",
    cursor: "pointer",
  },
  "& .selected-filter img": {
    cursor: "pointer",
    marginLeft: "10px",
    width: "8px",
    height: "8px",
    margin: "auto",
  },
  "& .selected-filter-box": {
    width: "auto",
    minWidth: "100px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  "& .selected-filter-container": {
    width: "22vw",
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    marginTop: "2%",
    marginLeft: "5%",
    overflow: "hidden",
  },
  "& .policies-text": {
    fontSize: fontSize.h24,
    fontWeight: fontWeight.semibold,
    paddingBottom: "1%",
    fontFamily: "Poppins",
  },
  "& .heading-text": {
    fontSize: fontSize.h24,
    fontWeight: fontWeight.semibold,
    paddingBottom: "1%",
    fontFamily: "Poppins",
  },
  "& .sub-heading-text": {
    fontSize: fontSize.h6,
    fontWeight: fontWeight.semibold,
    color: "#00000099",
    marginLeft: "1.5%",
    fontFamily: "Poppins",
    // opacity: "60%",
  },
  "& .sub-heading-content": {
    fontSize: fontSize.h6,
    fontWeight: fontWeight.medium,
    fontFamily: "Poppins",
    textAlign: "center",
  },

  "& .create-policy": {
    backgroundColor: bgColors.skyBlue,
    color: colors.white,
    width: "fit-content",
    padding: "0.8rem",
    maxHeight: "fit-content",
    "&:disabled": {
      backgroundColor: "#C3C3C3",
      fontWeight: fontWeight.bold,
    },
  },
  "& .create-project": {
    backgroundColor: bgColors.skyBlue,
    color: colors.white,
    width: "8vw",
  },
  "& .add-svg-icon": {
    fontSize: fontSize.p,
    colors: colors.bluishGreen,
  },
  "& Button": {
    borderRadius: "20px",
    textTransform: "none",
    color: colors,
    fontWeight: fontWeight.semibold,
    fontSize: fontSize.h6,
    fontFamily: "Poppins",
    "&:disabled": {
      opacity: "80%",
    },
  },
  "& .create-policy-label": {
    color: colors.white,
    backgroundColor: bgColors.skyBlue,
    display: "flex",
    justifyContent: "space-evenly",
    alignItems: "center",
    gap: "0.5rem",
    "&:disabled": {
      backgroundColor: "#C3C3C3",
      fontWeight: fontWeight.bold,
    },
  },
  "& .import-user-container": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    textAlign: "start",
  },
  "& .policies-container": {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    paddingBottom: "1%",
  },
  "& .count-box-Heading": {
    fontSize: fontSize.h4,
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
  },
  "& .to-long-textField": {
    fontFamily: "Poppins",
    maxHeight: "200px",
    overflowY: "auto",
  },
  "& .text-area-style": {
    width: "100%",
    // minHeight: "1.5rem",
    padding: "8px",
    fontSize: "16px",
    border: "1px solid rgba(0, 0, 0, .2)",
    webkitBackgroundClip: "padding-box",
    backgroundClip: " padding-box",
    borderRadius: "0.5rem",
    resize: "none",
    "&:focus": {
      borderColor: "black",
      boxShadow: "0 0 0 1px black",
    },
    "&:hover": {
      borderColor: "black",
    },
    "&::placeholder": {
      fontWeight: 500,
      fontFamily: "Poppins",
      // color:'rgba(0, 0, 0, .5)",'
      color: "black",
      opacity: "50%",
    },
  },
  "& .new-page-text-area": {
    width: "100%",
    padding: "8px",
    fontSize: "16px",
    border: "1px solid rgba(0, 0, 0, .2)",
    borderRadius: "0.5rem",
    resize: "none",
  },
  "& .count-box-size": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid lightgrey",
    height: "180px",
    borderRadius: "20px",
    boxShadow: "0 2px 16px #00000040",
  },
  "& .evidence-detail-box": {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  "& .evidence-detail-heading": {
    fontFamily: "Poppins",
    fontSize: fontSize.h5,
    fontWeight: fontWeight.medium,
    color: colors.black,
  },
  "& .evidence-detail-text": {
    fontFamily: "Poppins",
    fontSize: fontSize.h6,
    fontWeight: fontWeight.medium,
    color: colors.black,
    opacity: "70%",
  },
  "& .mapping-container": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "1% 0",
  },
  "& .mapping-heading": {
    fontWeight: fontWeight?.semibold,
    fontFamily: "Poppins",
    fontSize: "16px",
    marginTop: "2%",
    marginBottom: "2%",
  },
  "& .section-container": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "1% 0",
  },
  "& .section-heading": {
    fontWeight: fontWeight?.semibold,
    fontFamily: "Poppins",
    fontSize: fontSize.h18,
    marginTop: "1.5%",
    marginBottom: "1.5%",
    opacity: "80%",
  },
  "& .count-box-Title": {
    fontFamily: "Poppins",
    fontSize: fontSize.h1,
    color: colors.aquasky,
  },
  "& .data-grid-container": {
    fontFamily: "Poppins",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    paddingBottom: "1%",
    width: "100%",
  },
  "& .filter-count-box": {
    display: "flex",
    marginLeft: "0.2rem",
    gap: "0.5vw",
    alignItems: "center",
    flexDirection: "row",
  },
  "& .only-filter-container": {
    fontFamily: "Poppins",
    display: "flex",
    justifyContent: "end",
    alignItems: "flex-end",
    paddingBottom: "1%",
    maxWidth: "100%",
  },
  "& .drawer-container": {
    width: 350,
    height: "20vh",
    top: "100px",
    // padding: "2%",
  },

  "& .govern-dashboard-boxes": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid lightgrey",
    height: "100px",
    minWidth: "100px",
    borderRadius: "20px",
    // boxShadow: "0 2px 16px #00000040",
  },
  "& .govern-dashboard-box-heading": {
    width: "100%",
    textAlign: "start",
    fontWeight: 500,
    fontFamily: "Poppins",
    fontSize: fontSize.h18,
    margin: "0.5rem",
  },
  "& .govern-dashboard-count-heading": {
    fontSize: fontSize.h24,
    textAlign: "center",
    fontWeight: 600,
    fontFamily: "Poppins",
  },
  "& .govern-dashboard-count-subheading": {
    textAlign: "center",
    fontFamily: "Poppins",
    fontSize: "0.9rem",
    fontWeight: 500,
    whiteSpace: "pre-line",
  },
  "& .item-baseline": {
    display: "flex",
    alignItems: "flex-end",
  },
  "& .font-semibold": {
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
  },
  "& .filter-type": {
    paddingTop: "2%",
  },
  "& .policy-form-label": {
    display: "flex",
    gap: "4px",
    fontFamily: "Poppins",
    alignItems: "center",
  },
  "& .policy-text-field-label": {
    margin: "1% 0 1% 0",
    fontFamily: "Poppins",
  },
  "& .modal-input": {
    width: "100%",
    padding: "8px",
    marginTop: "4px",
    border: "1px solid rgba(0,0,0, .2)",
    borderRadius: "0.6rem",
    outline: "none",
    "&:focus": {
      borderColor: "black",
      boxShadow: "0 0 0 1px black",
    },
    "&:hover": {
      borderColor: "black",
    },
    "&::placeholder": {
      fontWeight: 500,
      fontFamily: "Poppins",
      color: "black",
      opacity: "50%",
    },
  },
  "& .modal-calender": {
    textDecoration: "none",
  },

  "& .modal-style": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },

  "& .action-btn-style": {
    fontSize: fontSize.h6,
    color: "#008C86",
  },

  "& .create-modal-heading": {
    fontSize: "1.25rem",
    fontFamily: "Poppins",
    fontWeight: "600",
    textAlign: "Left",
  },

  "& .compare-doc-heading": {
    fontSize: "1.25rem",
    fontFamily: "Poppins",
    fontWeight: "600",
    textAlign: "Left",
    padding: "2% 0 2% 0",
  },
  "& .modal-center-heading": {
    fontSize: "1.25rem",
    fontFamily: "Poppins",
    fontWeight: "600",
    margin: "2% 0 2% 0",
    textAlign: "center",
    padding: "2% 0 2% 0",
  },
  "& .remove-modal-center-heading": {
    fontSize: "0.9rem",
    fontFamily: "Poppins",
    fontWeight: "600",
    margin: "2% 0 2% 0",
    textAlign: "center",
    padding: "2% 0 2% 0",
  },
  "& .compare-doc-container-style": {
    width: "90%",
    padding: "2%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    borderRadius: "xl",
    height: "92vh",
    overflowY: "auto",
  },
  "& .required-icon": {
    color: "red",
    fontWeight: fontWeight.medium,
    marginLeft: "4px",
  },

  "& .policy-btn": {
    marginTop: "10px",
    borderRadius: "20px",
    width: "fit-content",
    height: "3rem",
    lineHeight: "10px",
    textTransform: "none",
    padding: "0px 2%",
    "&:hover": {
      backgroundColor: "#00b8a9",
    },
    "&:disabled": {
      backgroundColor: "#C3C3C3",
      fontWeight: fontWeight.bold,
    },
  },
  "& .submit-btn": {
    background: colors.aquasky,
    color: colors.white,
    borderRadius: "20px",
    width: "fit-content",
    lineHeight: "5px",
    textTransform: "none",
    padding: "5%",
  },
  "& .update-mapping-btn": {
    backgroundColor: "white",
    color: "black",
    minHeight: "fit-content",
    border: "0.5px solid rgba(12, 12, 12, 0.2)",
  },
  "& .policy-comments-heading": {
    fontSize: fontSize?.h4,
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
    opacity: "80%",
    width: "100%",
    borderBottom: "1px solid #EBEBEB",
    paddingLeft: "0.5rem",
  },
  "& .policy-comment-box": {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    padding: "1%",
    maxHeight: "300px",
    overflowY: "auto",
    paddingLeft: "0.8rem",
  },
  "& .about-policy-body": {
    fontFamily: "Poppins",
    border: "1px solid #E5E7EB",
    borderRadius: "0.5rem",
    padding: "4%",
  },
  "& .about-policy-details-body": {
    borderBottom: "1px solid #E5E7EB",
    width: "100%",
  },
  "& .details-box-main-heading": {
    fontFamily: "Poppins",
    fontSize: fontSize.h4,
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
  },
  "& .details-box-heading": {
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
    opacity: "70%",
  },
  "& .details-box-frequency-heading": {
    display: "flex",
    gap: "5px",
  },
  "& .policy-user-box": {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    paddingTop: "2%",
  },
  "& .policy-user-text": {
    fontSize: "14px",
    fontWeight: "600",
    fontFamily: "Poppins",
  },
  "& .edit-policy-user": {
    textTransform: "none",
    color: colors.bluishGreen,
    fontWeight: "500",
  },
  "& .edit-policy-user-text": {
    display: "flex",
    alignItems: "center",
    gap: "0.2rem",
  },
  "& .user-name-text": {
    fontSize: fontSize?.h6,
    opacity: "70%",
    fontFamily: "Poppins",
  },
  "& .note-box": {
    fontFamily: "Poppins",
    opacity: "80%",
    display: "flex",
    gap: "0.25rem",
    // alignItems: "center",
    alignItems: "baseline",
  },
  "& .note-heading": {
    color: "red",
    fontSize: fontSize?.h6,
  },
  "& .note-text": {
    fontFamily: "Poppins",
    fontSize: fontSize?.h7,
  },
  "& .mapping-accordian-heading": {
    display: "flex",
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
    fontSize: "16px",
    marginTop: "2%",
    marginBottom: "2%",
  },
  "& .details-box-text": {
    fontWeight: fontWeight.p1,
    fontFamily: "Poppins",
    opacity: "70%",
    marginLeft: "5px",
  },
  "& .details-box-text-frequency": {
    fontWeight: fontWeight.p1,
    fontFamily: "Poppins",
    opacity: "70%",
  },
  "& .policy-submit-btn": {
    background: colors.aquasky,
    color: colors.white,
    borderRadius: "20px",
    width: "max-content",
    maxHeight: "3rem",
    lineHeight: "10px",
    textTransform: "none",
    padding: "0px 4%",
  },
  "& .delete-btn": {
    background: colors.red,
    color: colors.white,
    opacity: "80%",
    borderRadius: "20px",
    width: "fit-content",
    lineHeight: "5px",
    textTransform: "none",
    padding: "5%",
  },
  "& .remove-btn": {
    background: colors.red,
    color: colors.white,
    opacity: "80%",
    borderRadius: "20px",
    width: "fit-content",
    lineHeight: "5px",
    textTransform: "none",
    padding: "5%",
  },
  "& .apply-filter-btn": {
    background: colors.aquasky,
    color: colors.white,
    width: "fit-content",
    marginTop: "10px",
    borderRadius: "20px",
    lineHeight: "10px",
    textTransform: "none",
    padding: "4%",
  },
  "& .less-padding-cancel-btn": {
    background: colors.white,
    marginTop: "10px",
    borderRadius: "20px",
    width: "fit-content",
    lineHeight: "0px",
    textTransform: "none",
    padding: "0 4%",
    height: "3rem",
    maxHeight: "3rem",
    color: colors.black,
    borderBottom: "1px solid rgba(0, 0, 0, .5)",
    "&:hover": {
      backgroundColor: "#00000030",
    },
  },
  "& .policy-cancel-btn": {
    background: colors.white,
    marginTop: "10px",
    borderRadius: "20px",
    width: "fit-content",
    lineHeight: "5px",
    textTransform: "none",
    color: colors.black,
    padding: "5%",
    borderBottom: "1px solid rgba(0, 0, 0, .5)",
    "&:hover": {
      backgroundColor: "#00000030",
    },
  },
  ".risk-value-box": {
    maxHeight: 200,
    maxWidth: 250,
    // background: colors.white,
    marginTop: "10px",
    borderRadius: "20px",
    width: "10rem",
    lineHeight: "5px",
    textTransform: "none",
    color: colors.black,
    padding: "1%",
    boxShadow: "0px 5px 5px rgb(0,0,0,0.3)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.1rem",
  },
  ".tabs-container": {
    width: "100%",
    overflow: "hidden",
    boxShadow: "none",
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
  },
  ".tab-text-color": {
    opacity: "80%",
    width: "100%",
    fontWeight: fontWeight.medium,
    position: "relative",
    // borderBottom: `1px solid ${bgColors.skyBlue}` ,
    "& .MuiTab-root.Mui-selected": {
      border: "2px solid #008C86",
      // borderBottom: "none",
      backgroundColor: "white",
    },
    "& .MuiTabs-flexContainer": {
      margin: 0,
      padding: 0,
      gap: "4px",
    },

    "& .MuiTabs-indicator": {
      display: "none",
    },
    "& .MuiTab-root": {
      border: `1px solid ${bgColors.skyBlue}`,
      borderBottom: "none",
      borderRadius: "16px 16px 0 0",
      padding: {
        xs: "8px 16px",
        sm: "10px 24px",
        md: "13px 35px",
      },
      minHeight: "40px",
      textTransform: "none",
      fontWeight: "bold",
      fontSize: {
        xs: "0.85rem",
        sm: "0.95rem",
        md: "1rem",
      },
      color: "black",
      gap: {
        xs: "2px",
        sm: "3px",
        md: "4px",
      },
    },

    "& .MuiTab-root.Mui-selected": {
      border: "1px solid #008C8680",
      // borderBottom: "none",
      backgroundColor: colors.aquasky,
    },
    ".auditor-svg-icon path": {
      // fill: colors.bluishGreen,
    },

    // "& .MuiTabs-flexContainer": {
    // borderBottom: "2px solid yellow",
    //   "& .Mui-selected": {
    //     backgroundColor: "white",
    //     borderBottom: "none",
    //     position: "relative",
    //     zIndex: 2,
    //   },
    // },
    // "& .MuiTab-root": {
    //   backgroundColor: "#f5f5f5",
    //   border: "1px solid yellow",
    //   borderBottom: "none",
    //   borderTopLeftRadius: "8px",
    //   borderTopRightRadius: "8px",
    //   padding: "8px 16px",
    //   marginRight: "4px",
    //   transition: "0.3s",
    // },
    // "& .Mui-selected": {
    //   backgroundColor: "white",
    //   borderBottom: "2px solid white",
    //   position: "relative",
    //   zIndex: 2,
    // },
    // "& .MuiTabs-indicator": {
    //   backgroundColor: colors?.bluishGreen,
    // },
    // "& .MuiTab-root": {
    //   color: "inherit",
    // },
    // "& .Mui-selected": {
    //   color: colors?.bluishGreen,
    // },
  },
  ".right-tabs-container": {
    marginTop: "5%",
    backgroundColor: "#E5E7EB",
    borderRadius: "10px",
    overflowY: "scroll",
    height: "300px",
  },
  "& .view-screen-subheading": {
    fontWeight: fontWeight?.semibold,
    fontFamily: "Poppins",
    fontSize: fontSize?.h5,
    marginBottom: "0.5rem",
  },
  "& .view-screen-subheading-text": {
    fontWeight: fontWeight?.medium,
    fontFamily: "Poppins",
    fontSize: fontSize?.h6,
    marginBottom: "1rem",
    color: colors?.gray,
  },
  "& .nested-tab-container": {
    border: `1px solid ${bgColors.skyBlue}`,
    padding: "2%",
    marginTop: "-5px",
    borderTopRightRadius: "0.7rem",
    borderBottomRightRadius: "0.7rem",
    borderBottomLeftRadius: "0.7rem",
  },
  "& .policy-comment-container": {
    position: "relative",
    bottom: "1rem",
    border: "1px solid #EDEDED",
    borderRadius: "1rem",
    marginTop: "1rem",
    paddingLeft: "1rem",
  },
  "& .comment-main-container": {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    borderBottom: "1px solid #EBEBEB",
  },
  "& .comment-container": {
    display: "flex",
    gap: "1rem",
    alignItems: "center",
  },
  "& .comment-section": {
    display: "flex",
    gap: "5px",
    alignItems: "center",
  },
  "& .comment-user-name": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#01D9D1",
    height: "30px",
    width: "30px",
    textAlign: "center",
    borderRadius: "50%",
    fontFamily: "Poppins",
    fontSize: fontSize.p,
    fontWeight: fontWeight.semibold,
    color: "#062D2B",
  },
  "& .comment-user-fullName": {
    fontSize: fontSize.h5,
    fontFamily: "Poppins",
  },
  "& .comment-user-type": {
    fontSize: fontSize.h5,
    fontFamily: "Poppins",
    opacity: "60%",
    backgroundColor: "#D9D9D9",
    padding: "0.5%",
    borderRadius: "20px",
  },
  "& .comment-user-duration": {
    fontSize: fontSize.h5,
    fontFamily: "Poppins",
    opacity: "60%",
  },
  "& .comment-action-menu": {
    width: "fit-content",
    backgroundColor: "#EDEDED",
    borderRadius: "10px",
    border: "1px solid #EDEDED",
  },
  "& .comment-input-current-user-box": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#D9D9D9",
    height: "40px",
    width: "40px",
    textAlign: "center",
    borderRadius: "30%",
    fontFamily: "Poppins",
    fontSize: fontSize.h5,
    fontWeight: fontWeight.semibold,
    color: "#062D2B",
    marginRight: "10px",
  },
  "& .mapping-container": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1%",
  },
  "& .mapping-heading": {
    fontWeight: fontWeight?.semibold,
    fontFamily: "Poppins",
    fontSize: "16px",
    marginTop: "2%",
    marginBottom: "2%",
  },
  "& .accordion-box": {
    fontFamily: "Poppins",
    display: "flex",
    flexDirection: "column",
    gap: "40px",
  },
  "& .accordion-container": {
    border: "1px solid #E5E7EB",
    backgroundColor: "#F7F7F7",
    borderRadius: "20px",
    fontFamily: "Poppins",
    padding: "2%",
    boxShadow: "none",
    borderBottomLeftRadius: "20px",
    borderBottomRightRadius: "20px",

    "&::before": {
      content: "none",
    },
    "&:last-of-type": {
      borderBottomLeftRadius: "20px",
      borderBottomRightRadius: "20px",
    },

    "&:first-of-type": {
      borderTopLeftRadius: "20px",
      borderTopRightRadius: "20px",
    },
  },
  "& .accordion-heading": {
    fontFamily: "Poppins",
    fontWeight: fontWeight.semibold,
    opacity: "90%",
  },
  "& .accordion-table": {
    border: "1px solid #E5E7EB",
    width: "90%",
    borderCollapse: "collapse",
    fontFamily: "Poppins",
    margin: "auto",
    tableLayout: "fixed",
  },

  "& .accordion-table thead tr th": {
    borderRight: "1px solid #E5E7EB",
  },
  "& .accordion-table-heading": {
    textAlign: "center",
    padding: "10px",
    fontWeight: "bold",
    backgroundColor: "#F7F7F7",
    borderBottom: "1px solid #E5E7EB",
  },
  "& .accordion-table-row": {
    padding: "10px",
    borderRight: "1px solid #E5E7EB",
    borderBottom: "1px solid #E5E7EB",
    textAlign: "center",
    wordWrap: "break-word" /* wrap long words */,
    overflowWrap: "break-word",
    maxWidth: "200px" /* or suitable width */,
    whiteSpace: "normal",
    fontFamily: "Poppins",
  },

  "& .accordion-link": {
    fontSize: fontSize?.p,
    color: "blue",
    cursor: "pointer",
    fontFamily: "Poppins",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  "& .mfa-checkbox-container": {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  "& .mfa-checkbox-row": {
    padding: "1%",
    display: "flex",
    alignItems: "center",
  },
  "& .mfa-checkbox": {
    height: "20px",
    width: "20px",
    marginRight: "2%",
  },
  "& .custom-lable": {
    fontWeight: fontWeight.medium,
    display: "flex",
    alignItems: "baseline",
    gap: "10px",
    fontFamily: "Poppins",
  },
  "& .category-btn": {
    paddingLeft: 0,
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins, sans-serif",
    alignSelf: "flex-start",
    marginTop: 1,
    color: colors.bluishGreen,
  },
  "& .risk-table": {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "1rem",
  },
  "& .risk-table thead": {
    backgroundColor: "#F4F4F4",
  },
  "& .risk-table thead tr": {
    width: " 100%",
    tableLayout: "fixed",
    borderCollapse: "collapse",
  },
  "& .risk-table thead tr th:nth-child(1)": {
    width: "20%",
  },
  "& .risk-table thead tr th:nth-child(2)": {
    width: "30%",
  },
  "& .risk-table thead tr th:nth-child(3)": {
    width: "50%",
  },
  "& .risk-table tbody tr": {
    width: " 100%",
    tableLayout: "fixed",
    borderCollapse: "collapse",
  },
  "& .risk-table tbody tr td:nth-child(1)": {
    width: "20%",
  },
  "& .risk-table tbody tr td:nth-child(2)": {
    width: "30%",
  },
  "& .risk-table tbody tr td:nth-child(3)": {
    width: "50%",
  },

  "& .risk-table th": {
    fontWeight: 600,
    fontSize: "16px",
    textAlign: "left",
    padding: "1rem",
    border: "none",
    borderRight: "1px solid #E0E0E0",
  },
  "& .risk-table th:first-child": {
    borderLeft: "1px solid #E0E0E0",
  },
  "& .risk-table td": {
    wordWrap: "break-word",
    whiteSpace: "normal",
    overflowWrap: "break-word",
    fontSize: "14px",
    padding: "1rem",
    border: "none",
    textAlign: "left",
    borderBottom: "1px solid #E0E0E0",
    borderRight: "1px solid #E0E0E0",
  },
  "& .risk-table td:first-child": {
    borderLeft: "1px solid #E0E0E0",
  },
  "& .nested-nav-header": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: "0.8rem",
  },
  "& .nested-nav-heading": {
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins, sans-serif",
    marginLeft: "1rem",
  },
  "&.nested-nav-menu-option-box": {
    width: "170px",
    backgroundColor: "white",
    borderRadius: "10px",
    border: "1px solid black",
  },
  "& .nested-nav-category-container": {
    display: "flex",
    flexDirection: "column",
    gap: "0.2rem",
    width: "100%",
    fontFamily: "Poppins",
  },
  "& .nested-nav-category-name": {
    fontSize: fontSize.h6,
    fontFamily: "Poppins, sans-serif",
  },
  "& .nested-nav-setting-container": {
    backgroundColor: "#FAFAFA",
    borderRadius: "0.7rem",
    padding: "1rem",
    boxShadow: "0px 4px 16px rgba(0,0,0,0.12)",
    border: "1.5px solid #D1D5DB",
    width: "100%",
    height: "100%",
    minHeight: "40vh",
  },
  "& .nested-nav-setting-heading": {
    fontSize: fontSize?.h4,
    fontWeight: fontWeight?.semibold,
    fontFamily: "Poppins",
  },
  "& .nested-nav-question-box-container": {
    backgroundColor: "#FAFAFA",
    borderRadius: "0.7rem",
    padding: "1rem",
    boxShadow: "0px 4px 16px rgba(0,0,0,0.12)",
    border: "1.5px solid #D1D5DB",
    width: "100%",
    height: "100%",
    // marginBottom: "2%",
  },
  "& .nested-nav-question-box": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FAFAFA",
    borderRadius: "0.4rem",
    padding: "1rem",
    boxShadow: "0px 0px 5px rgba(0, 0, 0, 0.1)",
    width: "100%",
  },
  "& .nested-nav-answer-box": {
    backgroundColor: "#FAFAFA",
    borderRadius: "0.4rem",
    padding: "1rem",
    boxShadow: "0px 0px 3px rgba(0, 0, 0, 0.1)",
    fontWeight: fontWeight.medium,
    color: colors?.black,
    fontSize: fontSize.h6,
    width: "100%",
  },
  "& .questionnaire-comment-btn": {
    fontSize: fontSize.h6,
    color: colors.black,
    minWidth: "auto",
    position: "relative",
    padding: 0,
  },
  "& .questionnaire-comment-count": {
    position: "absolute",
    top: "-6px",
    right: "-6px",
    backgroundColor: "red",
    color: "#fff",
    borderRadius: "50%",
    minWidth: "18px",
    height: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "10px",
    fontWeight: "bold",
    lineHeight: 1,
    zIndex: 1,
  },
  "& .questionnaire-evidence": {
    color: "black",
    cursor: "pointer",
    textDecoration: "none",
    fontSize: fontSize.h6,
    fontFamily: "Poppins",
    whiteSpace: "normal",
    wordBreak: "break-word",
    overflowWrap: "break-word",
    "&:hover": {
      textDecoration: "underline",
      color: colors.aquasky,
    },
  },
  "& .custom-label": {
    fontWeight: fontWeight.semibold,
    fontFamily: "Poppins",
    color: colors.black,
    fontSize: fontSize.h5,
    opacity: "70%",
  },

  "& .category-list": {
    listStyleType: "none",
    padding: "0",
    margin: "0",
  },
  "& .subcategory-list": {
    listStyleType: "none",
    padding: "0",
    margin: "0",
  },

  "& .category-item": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "2rem",
    paddingTop: "1rem",
    paddingBottom: "1rem",
    border: "1px solid #E0E0E0",
    marginTop: "1rem",
    borderRadius: "0.2rem",
    // marginBottom: "4px",
    fontSize: "14px",
    // backgroundColor: "#f9f9f9",
  },

  "& .subcategory-item": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "2rem",
    paddingTop: "1rem",
    paddingBottom: "1rem",
    // border: "1px solid #E0E0E0",
    // marginBottom: "4px",
    fontSize: "14px",
    // backgroundColor: "#f4f4f4",
  },

  "& .category-heading": {
    fontFamily: "Poppins",
    fontWeight: 600,
    fontSize: "16px",
    // textAlign: "center",
    padding: "1rem",
    paddingLeft: "2rem",
    paddingRight: "2rem",
    border: "none",
    // borderRight: "1px solid #E0E0E0",
    backgroundColor: "#F4F4F4",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  "& .risk-config-section-heading": {
    fontFamily: "Poppins",
    fontSize: fontSize.h4,
    fontWeight: fontWeight.bold,
    opacity: "80%",
    marginTop: "2%",
  },

  "& .category-data": {
    fontFamily: "Poppins, sans-serif",
    // fontWeight: fontWeight.semibold,
    fontSize: fontSize.h5,
    flexGrow: 1,
    overflowWrap: "break-word",
    wordBreak: "break-word",
  },
  "& .subcategory-data": {
    fontSize: fontSize.h5,
    fontWeight: fontWeight.medium,
    fontFamily: "Poppins, sans-serif",
    whiteSpace: "normal",
    wordBreak: "break-word",
    overflowWrap: "break-word",
    maxWidth: "100%",
  },
  "& .user-label": {
    display: "flex",
    alignItems: "center",
    gap: "5px",
    fontFamily: "Poppins",
  },
  "& .user-label-email": {
    fontSize: fontSize.p,
    opacity: "80%",
    fontFamily: "Poppins",
  },
  "& .text-btn": {
    fontSize: fontSize.h6,
    color: colors.bluishGreen,
  },
  "& .upload-btn": {
    background: colors.white,
    marginTop: "4px",
    borderRadius: "20px",
    width: "12rem",
    height: "4rem",
    color: colors.black,
    fontWeight: fontWeight.medium,
    lineHeight: "10px",
    textTransform: "none",
    border: "1px solid #DADCE0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
  },
  "& .control-details-container": {
    display: "flex",
    minHeight: "250px",
    border: "1px solid #00000030",
    borderRadius: "10px",
    height: "100%",
  },
  "& .faded-row": {
    opacity: 0.6, // 60% opacity
    cursor: "default",
  },
  "& .text-hover": {
    cursor: "pointer",
    textDecoration: "none",
    "&:hover": {
      textDecoration: "underline",
      color: colors.bluishGreen,
    },
  },
  "& .nested-filter-container": {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },

  "& .dashboard-card-container": {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "100%",
    height: "100%",
    minHeight: 200,
    maxHeight: 640,
    padding: "1rem",
    borderRadius: "20px",
    backgroundColor: "white",
    // boxShadow: "0 2px 16px #00000030",
    boxShadow: " 0px 4px 4px 0px rgba(0, 0, 0, 0.25)",
    border: "1px solid rgba(0, 0, 0, 0.05)",
  },
  "& .dashboard-card-heading": {
    textAlign: "start",
    fontWeight: 600,
    fontFamily: "Poppins",
    fontSize: fontSize.h4,
    marginLeft: "1%",
  },
  "& .dashboard-card-sub-heading": {
    textAlign: "start",
    fontWeight: 600,
    fontFamily: "Poppins",
    fontSize: fontSize.h6,
  },
  "& .dashboard-chart-container": {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    alignItems: "center",
    // paddingRight: 8,
    fontFamily: "Poppins",
  },
  "& .dashboard-progress-bar": {
    width: "100%",
    height: "14px",
    borderRadius: "20px",
    backgroundColor: "#eee",
    display: "flex",
    overflow: "hidden",
    marginTop: "8px",
    marginBottom: "8px",
  },
  "& .dashboard-progress-bar-item-first": {
    backgroundColor: "#02AAA3",
    transition: "width 0.5s ease",
  },
  "& .dashboard-progress-bar-item-second": {
    backgroundColor: "#01D9D1",
    transition: "width 0.5s ease",
  },
  "& .heading-container": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  "& .chart-label-container": {
    display: "flex",
    alignItems: "center",
    gap: "0.4rem",
  },
  "& .chart-label-color-box": {
    width: "1rem",
    height: "1rem",
    borderRadius: "2px",
    transition: "all 0.3s ease",
  },
  "& .config-category-item": {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0.75rem 1rem",
    borderRadius: "0.4rem",
    border: "1px solid #E0E0E0",
    boxShadow: "none",
    backgroundColor: "white",
    transition: "box-shadow 0.3s, border-color 0.3s, background-color 0.3s",
    userSelect: "none",
    gap: "0.5rem",
  },
  "& .config-category-text": {
    fontFamily: "Poppins, sans-serif",
    // fontWeight: 600,
    fontSize: fontSize.h5,
    color: "black",
    flexGrow: 1,
    overflowWrap: "break-word",
    wordBreak: "break-word",
  },
  "& .audit-progress-graph-container": {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",

    // height: 250,
    border: "1px solid #00000030",
    borderRadius: "20px",
    boxShadow:
      "0 4px 8px 0 rgba(0, 0, 0, 0.25), 0 6px 12px 0 rgba(0, 0, 0, 0.24);",
    fontFamily: "Poppins",
    padding: "1rem",
    gap: "1rem",
  },

  "& .audit-progress-graph-heading": {
    fontSize: fontSize.h18,
    fontWeight: fontWeight.medium,
    fontFamily: "Poppins",
    textAlign: "left",
  },

  "& .search-input": {
    maxHeight: "2.5rem",
    width: "90%",
    borderRadius: "12px",
    fontFamily: "Poppins",
    boxShadow: "0px 6px 18px -12px rgba(0, 0, 0.5)",
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      border: "1px solid rgba(0,0,0.1)",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      border: "1px solid rgba(0,0,0.1)",
    },
    "&.Mui-error .MuiOutlinedInput-notchedOutline": {
      border: "1px solid rgba(0,0,0.1)",
    },
  },

  "& .search-input-container": {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "end",
    gap: "0.2rem",
    position: "relative",
    marginBottom: "2%",
  },

  "& .search-input-option-container": {
    position: "absolute",
    top: "100%",
    width: "65%",
    maxHeight: 260,
    overflowY: "auto",
    zIndex: 10,
    borderRadius: "8px",
  },
  "& .user-greeting": {
    display: "flex",
    alignItems: "center",
    padding: "6px 14px",
    borderRadius: "999px",
    backgroundColor: "#F5F7FA",
    border: "1px solid #E5E7EB",
  },
  "& .greeting-text": {
    fontFamily: "Poppins",
    fontSize: "14px",
    fontWeight: 400,
    color: "#4B5563",
  },
  "& .greeting-name": {
    fontWeight: 600,
    marginLeft: "4px",
    color: "#0F766E", // teal-ish
  },
  "& .file-upload-btn": {
    color: "white",
    height: "56px",
    width: "15vw",
    borderRadius: "15px",
    border: "1px solid black",
    borderStyle: "dotted",
    cursor: "pointer",
    textAlign: "center",
    padding: "10px",
    display: "flex",
    justifyContent: "space-around",
  },
  "& .filter-list-not-found-msg": {
    fontFamily: "Poppins",
    margin: "4%",
  },
  "& .table-row-hover": {
    cursor: "pointer",
    textDecoration: "none",
    textAlign: "start",
    "&:hover": {
      textDecoration: "underline",
      color: colors.darkgreen,
    },
  },
  "& .tooltip-user-container": {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  "& .tooltip-user-fullName": {
    fontFamily: "Poppins",
    fontSize: fontSize.h6,
  },
  "& .tooltip-user-email": {
    fontFamily: "Poppins",
    fontSize: fontSize.h7,
  },
  "& .error-charcount-box": {
    display: "flex",
    justifyContent: "space-between",
  },
  "& .active-text": {
    backgroundColor: "#D9F6D3",
    // fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "5px 10px",
    borderRadius: "1rem",
    textAlign: "center",
    whiteSpace: "nowrap",
    fontFamily: "Poppins",
  },
  "& .inactive-text": {
    // fontSize: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1D0D6",
    padding: "5px 10px",
    borderRadius: "1rem",
    textAlign: "center",
    fontFamily: "Poppins",
  },
}));

const CustomeDataGrid = styled(DataGrid)(() => ({
  "& .MuiDataGrid-cell": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  "& .MuiDataGrid-columnHeader, & .MuiDataGrid-cell": {
    backgroundColor: "red !impotant",
  },

  "& .MuiDataGrid-virtualScroller": {
    overflowX: "auto !important",
  },
  "& .MuiDataGrid-cell, & .MuiDataGrid-columnHeader": {
    whiteSpace: "nowrap",
  },

  // /* Sticky columns */
  // "& .MuiDataGrid-cell[data-field='Risk ID'], & .MuiDataGrid-columnHeader[header-name='evidenceId']":
  //   {
  //     position: "sticky",
  //     left: 0,
  //     backgroundColor: "#f0f0f0",
  //     zIndex: 1,
  //     boxShadow: "2px 0 5px -2px rgba(0, 0, 0, 0.2)",
  //     backgroundColor:'red !important',
  //   },
  // "& .MuiDataGrid-cell[data-field='category'], & .MuiDataGrid-columnHeader[data-field='category']":
  //   {
  //     position: "sticky",
  //     left: 100,
  //     backgroundColor: "#f0f0f0",
  //     zIndex: 1,
  //     boxShadow: "2px 0 5px -2px rgba(0, 0, 0, 0.2)",
  //   },
  // "& .MuiDataGrid-cell[data-field='custom'], & .MuiDataGrid-columnHeader[data-field='custom']":
  //   {
  //     position: "sticky",
  //     left: 300,
  //     backgroundColor: "#f0f0f0",
  //     zIndex: 1,
  //     boxShadow: "2px 0 5px -2px rgba(0, 0, 0, 0.2)",
  //   },

  // /* General Styles */
  // "&": {
  //   width: "100%",
  //   fontFamily: "Poppins",
  // },
  // "& .MuiDataGrid-cell:focus, & .MuiDataGrid-columnHeader:focus": {
  //   outline: "none",
  // },
  // "& .MuiDataGrid-cell:focus-within": {
  //   outline: "none",
  // },

  // /* Checkbox Customization */
  // "& .MuiDataGrid-checkboxInput": {
  //   display: "flex",
  //   alignItems: "center",
  //   justifyContent: "center",
  //   cursor: "pointer",
  //   width: "18px",
  //   height: "18px",
  //   borderRadius: "4px",
  //   backgroundColor: "#fff",
  //   position: "relative",
  // },

  // /* Checked Checkbox Styles */
  // "& .Mui-checked .MuiDataGrid-checkboxInput": {
  //   backgroundColor: "#C1E4E2 !important",
  //   borderColor: "#008C87 !important",
  // },

  // /* Avatar Group Styling */
  // "& .MuiAvatarGroup-avatar": {
  //   fontSize: "1rem", // Adjust font size
  //   display: "flex",
  //   alignItems: "center",
  //   justifyContent: "center",
  //   backgroundColor: "#008C87", // Example color
  //   color: "#fff", // Example text color
  //   textAlign: "right",
  // },

  // /* Row Styling */
  // "& .MuiDataGrid-row": {
  //   display: "flex",
  //   alignItems: "center",
  //   paddingBottom: "5px",
  //   borderBottom: "1px solid #b3b3b3", // Adjust border color
  // },

  // /* Column Header Styling */
  // "& .MuiDataGrid-columnHeader": {
  //   padding: "10px",
  //   color: "#333", // Text color
  //   fontSize: "1rem", // Adjust font size
  //   textAlign: "left",
  //   backgroundColor: "#f9f9f9", // Background color
  //   borderCollapse: "collapse",
  // },

  // /* Cell Styling */
  // "& .MuiDataGrid-cell": {
  //   color: "#333", // Text color
  //   justifyContent: "flex-start", // Align text to start
  //   maxWidth: "100%",
  //   whiteSpace: "normal", // Allow wrapping of text
  //   wordBreak: "break-word", // Break long words
  //   display: "flex",
  //   alignItems: "center",
  //   lineHeight: "normal", // Adjust line height
  //   borderTop: "none", // Remove top border
  // },

  // New CSS ENds
  "& ": {
    fontFamily: "Poppins",
  },
  "& .MuiDataGrid-cell:focus, & .MuiDataGrid-columnHeader:focus": {
    outline: "none",
  },
  "& .MuiDataGrid-cell:focus-within": {
    outline: "none",
  },
  "& .MuiDataGrid-checkboxInput": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    width: "18px",
    height: "18px",
    borderRadius: "4px",
    backgroundColor: "#fff",
    position: "relative",
  },
  "& .MuiDataGrid-virtualScroller": {
    overflowX: "auto !important",
  },
  "& .Mui-checked .MuiDataGrid-checkboxInput": {
    backgroundColor: "#C1E4E2 !important",
    borderColor: "#008C87 !important",
  },
  "& .Mui-checked .MuiSvgIcon-root": {
    color: "#008C87 !important",
  },
  "& .MuiCheckbox-root": {
    color: "#008C87 !important",
  },
  "& .MuiCheckbox-root.Mui-checked": {
    backgroundColor: "#C1E4E2 !important",
    borderColor: "#008C87 !important",
  },
  "& .MuiButtonBase-root-MuiButton-root": {
    fontFamily: "Poppins",
    height: "33px",
    border: "2px solid #01D9D1",
    minWidth: "100px",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    borderRadius: "20px",
    color: "black",
  },
  "& .MuiDataGrid-columnHeader:hover .MuiDataGrid-sortIcon": {
    opacity: "0 !important",
    pointerEvents: "none",
    display: "none",
  },
  "& .MuiDataGrid-columnHeader .MuiDataGrid-sortIcon": {
    opacity: "0 !important",
    pointerEvents: "none",
    display: "none",
  },
  "& .MuiAvatarGroup-avatar": {
    fontSize: fontSize.h6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors?.aquasky,
    color: "white",
    textAlign: "right",
  },
  "& .avatar-group": {
    display: "flex",
    justifyContent: "flex-end",
    flexDirection: "row-reverse",
    fontSize: fontSize.h4,
  },
  "& .datagrid-column-style": {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "end",
  },

  "& .avatar-group2": {
    display: "flex",
    justifyContent: "center",
    flexDirection: "row-reverse",
    fontSize: fontSize.h4,
  },
  "& .MuiAvatarGroup-avatar.MuiAvatar-root": {
    fontSize: "0.9rem",
    textAlign: "right",
    display: "flex",
    flexDirection: "column",
  },

  "& .MuiDataGrid-row": {
    display: "flex",
    alignItems: "center",
    paddingBottom: "5px",
    borderBottom: "1px solid black",
  },
  "& .datagrid-column-title": {
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "end",
    cursor: "pointer",
  },
  "& .framework-column": {
    display: "flex",
    alignItems: "center",
    gap: 2,
    fontFamily: "Poppins",
  },

  "& .css-1fgl3fb-MuiDataGrid-root": {
    border: "none",
  },
  "& .MuiDataGrid-root": {
    borderRadius: "5px",
    textAlign: "start",
  },
  "& .MuiDataGrid-columnHeader": {
    backgroundColor: "#f0f0f0",
  },
  "& .MuiDataGrid-columnHeader": {
    padding: "10px",
    color: "#333",
    fontSize: fontSize.h5,
    textAlign: "left",
    backgroundColor: "#f0f0f0",
    borderCollapse: "collapse",
  },

  "& .MuiDataGrid-cell": {
    color: "#333",
    borderTop: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  "& .MuiCheckbox-root": {
    padding: "0",
  },
  "& .MuiDataGrid-footerContainer": {
    borderTop: "1px solid #b3b3b3",
  },
  "& .MuiDataGrid-cellCheckbox": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  "& .MuiDataGrid-cell": {
    justifyContent: "flex-start",
    maxWidth: "100%",
    whiteSpace: "normal",
    wordBreak: "break-word",
    display: "flex",
    alignItems: "center",
    lineHeight: "normal",
    borderTop: "none",
  },
  "& .datagrid-row-data-start": {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  "& .active-text": {
    backgroundColor: "#D9F6D3",
    fontSize: "12px",
    padding: "5px 10px",
    borderRadius: "20px",
    textAlign: "center",
  },
  "& .inactive-text": {
    backgroundColor: "#F1D0D6",
    padding: "5px 10px",
    borderRadius: "20px",
    textAlign: "center",
  },
  "& .title-style": {
    display: "flex",
    alignItems: "start",
    justifyContent: "space-between",
    flexDirection: "column",
    position: "relative",
    ":hover": {
      "& .hover-image": {
        display: "block",
      },
    },
  },
  "& .title-start": {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  "& .sub-text": {
    fontWeight: fontWeight.medium,
    fontSize: fontSize.p,
    color: "grey",
    marginTop: "5px",
    marginBottom: "2%",
  },
  "& .doc-type-style": {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    fontFamily: "Poppins",
  },
  "& .project-name": {
    marginBottom: "4px",
    fontFamily: "Poppins",
    textAlign: "start",
  },
  "& .filter-container-style": {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "end",
    paddingBottom: "1%",
  },

  "& .project-name": {
    marginBottom: "4px",
    fontFamily: "Poppins",
    textAlign: "start",
  },
  "& .hover-image": {
    display: "none",
    cursor: "pointer",
    transform: "translateY(-50%)",
    ":hover": {
      "& .hover-image": {
        display: "flex",
        alignItems: "center",
      },
    },
  },
  "& .table-row-hover": {
    cursor: "pointer",
    textDecoration: "none",
    "&:hover": {
      textDecoration: "underline",
      color: colors.aquasky,
    },
  },
  "& .edit-icon": {
    filter: "brightness(0) invert(0)",
    cursor: "pointer",
  },
}));

const Item = styled(Paper)(({ theme }) => ({
  ...theme.typography.body2,
  padding: theme.spacing(1),
  paddingTop: "8%",
  boxShadow: "none",
  textAlign: "center",
  color: theme.palette.text.secondary,
  ...theme.applyStyles("dark", {
    backgroundColor: "#1A2027",
  }),
}));

const CustomeModal = styled(Modal)({
  "& ": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  "& .modal-container": {
    width: "40%",
    // maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    borderRadius: "10px",
    bgcolor: "white",
    border: "1px solid #01D9D1",
    boxShadow: "md",
    padding: "2%",
  },
  "& .modal-header": {
    flexShrink: 0,
    padding: "1%",
    paddingBottom: "5%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  "& .modal-body": {
    flexGrow: 1,
    overflowY: "auto",
    maxHeight: "60vh",
    padding: "1%",
  },
  "& .modal-footer": {
    flexShrink: 0,
    padding: "1%",
    display: "flex",
    justifyContent: "flex-start",
    gap: "1rem",
  },
  "& .control-mapping-container": {
    width: "40%",
    padding: "2%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    marginBottom: "1%",
    maxHeight: "92vh",
    overflowY: "auto",
    borderRadius: "20px",
  },
  "& .control-mapping-container-extra-width": {
    width: "40%",
    padding: "2%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    marginBottom: "1%",
    maxHeight: "92vh",
    overflowY: "auto",
    borderRadius: "20px",
  },
  "& .modal-container-style": {
    width: "40%",
    padding: "2%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    borderRadius: "20px",
    backgroundColor: "white",
  },
  "& .compare-doc-modal-style": {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "92vh",
    marginTop: "8vh",
    borderRadius: "20px",
  },
  "& .create-control-modal-container": {
    padding: "2%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    borderRadius: "20px",
    backgroundColor: "white",
    maxHeight: "90vh",
    overflowY: "auto",
  },
  "& .objective-modal-container": {
    width: "40%",
    padding: "2%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    borderRadius: "1rem",
  },
  "& .delete-modal-container": {
    padding: "2%",
    width: "30%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    borderRadius: "20px",
    backgroundColor: "white",
    maxHeight: "85vh",
  },
  "& .download-modal-container": {
    padding: "2%",
    width: "30%",
    boxShadow: "md",
    border: "1px solid #01D9D1",
    borderRadius: "20px",
    backgroundColor: "white",
    maxHeight: "85vh",
  },
  "& .kpi-modal-container": {
    width: "40%",
    height: "85vh",
    padding: "2%",
    boxShadow: "md",
    borderRadius: "0.8rem",
    border: "1px solid #01D9D1",
    // "&::-webkit-scrollbar": {
    //   width: "1rem",
    // },
    // "&::-webkit-scrollbar-thumb": {
    //   backgroundColor: "#888888",
    //   borderRadius: "1rem",
    //   opacity: 90
    // },
    // "&::-webkit-scrollbar-thumb:hover": {
    //   backgroundColor: "#555",
    // },
    // "&::-webkit-scrollbar-track": {
    //   background: "#f1f1f1",
    // },  },
  },
});

const CustomTextField = styled(TextField)(({ theme }) => ({
  "& .MuiOutlinedInput-root": {
    borderRadius: "0.5rem",
    borderColor: "rgba(0, 0, 0, 0.23)",
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      borderColor: "black",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      borderColor: "black",
    },
    "&.Mui-error .MuiOutlinedInput-notchedOutline": {
      borderColor: "black !important",
    },
  },
  "& .MuiInputBase-input": {
    fontSize: "16px",
    fontWeight: "500",
    fontFamily: "Poppins, sans-serif",
    "&::placeholder": {
      fontWeight: 500,
      fontFamily: "Poppins",
      opacity: 0.5,
    },
  },
  "& .MuiFormHelperText-root": {
    color: "black",
  },
}));

const CustomTextArea = styled(TextareaAutosize)(({}) => ({
  display: "block",
  width: "100%",
  // height: "2rem",
  padding: "8px",
  maxHeight: 150,
  overflowY: "auto",
  fontSize: fontSize.h5,
  fontWeight: fontWeight.medium,
  border: "1px solid rgba(0, 0, 0, .2)",
  borderRadius: "0.5rem",
  resize: "none",
  webkitBackgroundClip: "padding-box",
  backgroundClip: "padding-box",
  "&:focus": {
    outline: "none",
    borderColor: "black",
    boxShadow: "0 0 0 1px black",
  },
  "&::placeholder": {
    fontWeight: 500,
    fontFamily: "Poppins",
    color: "rgba(0, 0, 0, .5)",
    // color: "black",
    opacity: 0.8,
  },
}));
export {
  fontSize,
  fontWeight,
  colors,
  GlobleStyle,
  bgColors,
  CustomeDataGrid,
  Item,
  CustomeModal,
  CustomTextField,
  CustomTextArea,
};
